server:
  port: 8863
spring:
  application:
      name: eureka-server-peer3
  profiles:
    active: peer3
eureka:
  instance:
    hostname: eureka-server-peer3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-peer2:8862/eureka/,http://eureka-server-peer3:8861/eureka/