server:
  port: 8862
spring:
  application:
      name: eureka-server-peer2
  profiles:
    active: peer2
eureka:
  instance:
    hostname: eureka-server-peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-peer2:8861/eureka/,http://eureka-server-peer3:8863/eureka/